---
log_folder: '/home/vadim/Documents/logs/new_logs'
report_file: 'default.conf/report.yml'


templates: 'default.conf/templates/'
log_formats: 'default.conf/log_formats.yml'
api_file: 'default.conf/api.json'